<?php
require_once 'config.php';
require_once 'functions.php';

// Get webhook token from URL parameter
$webhook_token = $_GET['token'] ?? '';

if (empty($webhook_token)) {
    http_response_code(400);
    echo json_encode(['status' => 'error', 'message' => 'Webhook token required']);
    exit;
}

// Get sub-admin settings by token
$conn = getDBConnection();
$stmt = $conn->prepare("SELECT s.*, a.id as admin_id FROM sub_admin_settings s 
                       INNER JOIN admins a ON s.admin_id = a.id 
                       WHERE s.webhook_token = ? AND a.status = 'active'");
$stmt->bind_param("s", $webhook_token);
$stmt->execute();
$result_settings = $stmt->get_result();
$settings = $result_settings->fetch_assoc();
$stmt->close();

if (!$settings) {
    $conn->close();
    http_response_code(401);
    echo json_encode(['status' => 'error', 'message' => 'Invalid webhook token']);
    exit;
}

$sub_admin_id = $settings['admin_id'];

// Get POST data
$postData = file_get_contents('php://input');
$data = json_decode($postData, true);

// If JSON decode fails, try $_POST
if ($data === null) {
    $data = $_POST;
}

// Process the data through your function
$result = processIncomingData($data);


if ($result && isset($result['text']) && isset($result['number'])) {
    $text = $result['text'];
    $phone = $result['number'];
    $name = isset($result['name']) ? $result['name'] : '';
    
    // Clear reply.log file for new webhook request (with error handling)
    $logFile = __DIR__ . '/reply.log';
    @file_put_contents($logFile, '', LOCK_EX);
    
    // Validate phone number - only process if starts with 92 or +92
    $phoneClean = ltrim($phone, '+'); // Remove + if present for checking
    if (substr($phoneClean, 0, 2) !== '92') {
        // Invalid phone number format - return without processing
        http_response_code(200);
        echo json_encode(['status' => 'ignored', 'message' => 'Phone number does not start with 92 or +92']);
        exit;
    }

    // Ignore-list check (per sub-admin): match by last 6 digits
    $ignoreListRaw = $settings['ignore_numbers'] ?? '';
    if (isIgnoredPhone($phone, $ignoreListRaw)) {
        $conn->close();
        http_response_code(200);
        echo json_encode([
            'status' => 'ignored',
            'message' => 'Phone matched ignore list (last 6 digits)'
        ]);
        exit;
    }
    
    // Check if incoming message contains "stop" command (case insensitive)
    $incomingTextLower = strtolower(trim($text));
    if ($incomingTextLower === 'stop' || $incomingTextLower === 'unsubscribe') {
        // User wants to stop - don't process or send any message
        $conn->close();
        http_response_code(200);
        echo json_encode(['status' => 'stopped', 'message' => 'User requested to stop']);
        exit;
    }
    
    // Check if phone number already exists in leads table for this sub-admin
    $existingLead = checkPhoneExists($phone, $sub_admin_id);
    
    $replyMessage = null;
    
    if ($existingLead) {
        // Phone exists - get reply from another function with sub-admin settings
        $replyMessage = getReplyMessage($text, $phone, $settings);
        
        // Check if reply contains "stop" (case insensitive) - if yes, don't send message
        $replyLower = strtolower($replyMessage);
        if (stripos($replyLower, 'stop') !== false) {
            // Reply contains "stop" - don't send message, just log it
            $replyMessage = 'stop';
            
            // Log that message was stopped
            logMessage([
                'sub_admin_id' => $sub_admin_id,
                'phone' => $phone,
                'name' => $name,
                'message' => 'Message stopped - AI reply contained "stop"',
                'type' => 'sent'
            ], 'sent');
        } else {
            // Add message to queue instead of sending directly
            addMessageToQueue($sub_admin_id, $phone, $name, $replyMessage, $settings);
            
            // Log queued message
            logMessage([
                'sub_admin_id' => $sub_admin_id,
                'phone' => $phone,
                'name' => $name,
                'message' => $replyMessage . ' (Queued)',
                'type' => 'sent'
            ], 'sent');
        }
    } else {
        // New phone number - insert into leads table with name and sub_admin_id
        insertLead($phone, $text, $sub_admin_id, $name);
        
        // Send welcome message to new lead (generated by AI)
        $welcomeMessage = getWelcomeMessage($name, $settings);
        
        // Check if welcome message contains "stop" - if yes, don't send
        $welcomeLower = strtolower($welcomeMessage);
        if (stripos($welcomeLower, 'stop') !== false) {
            // Welcome message contains "stop" - don't send
            $welcomeMessage = 'stop';
            
            // Log that welcome message was stopped
            logMessage([
                'sub_admin_id' => $sub_admin_id,
                'phone' => $phone,
                'name' => $name,
                'message' => 'Welcome message stopped - AI reply contained "stop"',
                'type' => 'sent'
            ], 'sent');
        } else {
            // Add welcome message to queue instead of sending directly
            addMessageToQueue($sub_admin_id, $phone, $name, $welcomeMessage, $settings);
            
            // Log queued welcome message
            logMessage([
                'sub_admin_id' => $sub_admin_id,
                'phone' => $phone,
                'name' => $name,
                'message' => $welcomeMessage . ' (Queued)',
                'type' => 'sent'
            ], 'sent');
        }
        
        // Set reply message for chat history
        $replyMessage = $welcomeMessage;
    }
    
    // Log received message (for both new and existing leads)
    logMessage([
        'sub_admin_id' => $sub_admin_id,
        'phone' => $phone,
        'name' => $name,
        'message' => $text,
        'type' => 'received'
    ], 'received');
    
    // Maintain chat history (include reply if exists)
    $result['reply'] = $replyMessage;
    $result['sub_admin_id'] = $sub_admin_id;
    saveChatHistory($phone, $text, $result);
    
    $conn->close();
    
    // Return success response
    http_response_code(200);
    echo json_encode(['status' => 'success', 'message' => 'Processed']);
} else {
    // Invalid data
    http_response_code(400);
    echo json_encode(['status' => 'error', 'message' => 'Invalid data format']);
}
?>

